org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.208
loader_version_range=[1,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=kubejs_tfc
mod_name=KubeJS TFC
mod_license=MIT
mod_version=2.0.0
mod_group_id=io.github.notenoughmail.kubejstfc
mod_authors=NotEnoughMail
mod_description=KubeJS compatibility for TFC

tfc_version_range=[4.0.17-beta,)
kube_version_range=[2101.7.2-build.343,)
# firmalife_version_range=[2.1.12,)

# Dependencies
#     TFC
# https://www.curseforge.com/minecraft/mc-mods/terrafirmacraft/files
tfc_file=7452541
cyanide_file=5782674
patchi_file=6842247
jade_file=6853386
jei_version=19.25.0.322

#     Kube
kubejs_version=2101.7.2-build.343
rhino_version=2101.2.7-build.81
entityjs_file=6923414
geckolib_file=7023453

#     Addons
# https://www.curseforge.com/minecraft/mc-mods/firmalife/files
# firmalife_identifier=6817407
# https://www.curseforge.com/minecraft/mc-mods/tfc-rosia/files
# rosia_identifier=null
# https://www.curseforge.com/minecraft/mc-mods/arborfirmacraft/files
arbor_file=7314761
# https://www.curseforge.com/minecraft/mc-mods/precision-prospecting/files
precpros_file=7020720
# https://www.curseforge.com/minecraft/mc-mods/beneath/files
# beneath_identifier=5878796
# https://www.curseforge.com/minecraft/mc-mods/tfc-artisanal/files
# artisanal_identifier=6920813
