modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Notenoughmail/KubeJS-TFC/issues"

[[mods]]
    modId="kubejs_tfc"
    version="${file.jarVersion}"
    displayName="KubeJS TFC"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/kubejs-tfc"
    logoFile="kubejs_tfc_icon.png"
    credits="DoubleDoorDevelopment/Claycorp for the foundation (https://github.com/DoubleDoorDevelopment/OversizedItemInStorageArea) of the container limiter functionality"
    authors="Not Enough Mail"
    description='''KubeJS Integration for TFC'''

[[dependencies.kubejs_tfc]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kubejs_tfc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kubejs_tfc]]
    modId = "tfc"
    mandatory = true
    versionRange = "[2.1.14,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.kubejs_tfc]]
    modId = "kubejs"
    mandatory = true
    versionRange = "[1802.5.4-build.521,)"
    ordering = "AFTER"
    side = "BOTH"