modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Notenoughmail/KubeJS-TFC/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/kubejs-tfc"
    logoFile="kubejs_tfc_icon.png"
    credits="DoubleDoorDevelopment/Claycorp for the foundation (https://github.com/DoubleDoorDevelopment/OversizedItemInStorageArea) of the container limiter functionality"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependecies.${mod_id}]]
    modId = "tfc"
    mandatory = true
    versionRange = "${tfc_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "kubejs"
    mandatory = true
    versionRange = "{kube_version_range}"
    ordering = "NONE"
    side = "BOTH"